### ISSUE TITLE
You must own this item to write a Customer Review

### ISSUE THREAD

**Issue by marbetschar** [neilmorton/GetRated#2]
Hi there,

I've intergrated your `GetRated` library into my app. The app is already released to the App Store and I've invited some people using promo codes. If I manually want to rate the app in the store now by calling `getRated.sharedInstance().openRatingsPageOnAppStore()` the App store claims: "You must own this item to write a Customer Review".

Do you have any idea how to fix this?

![IMG_4290](https://user-images.githubusercontent.com/392542/59179628-e7970200-8b62-11e9-9ed5-b0549cc5c35b.jpeg)

**Comment by neilmorton** [comment]
Hi Marco, 

Firstly, this isn't an issue with `GetRated`. If the user manually went to the App Store, searched for your app, and tapped 'Write a Review', you will see this exact same message. Similarly, if they tapped a star rating, they would see a message 'You do not own this item. To rate this item, you must own it.'

Why does this happen at all? When a user has used a promo code to download the app, Apple treats them as not 'owning' the app. Only if a user chooses to download an app normally from the store does it work. Once a promo code has been used, it is not possible for that user to submit a review at all. It is the same scenario as when a user hasn't downloaded an app yet, if they try to review or rate on the App Store, the same message appears, only if they later installed it normally, they would then be able to rate / review.

**Comment by marbetschar** [comment]
@neilmorton thank you very much for clarification! I just came across a similar statement while searching for this issue in the web - unfortunately.

Wasn't aware of this, lesson learned. Thanks a bunch!

**Comment by marbetschar** [comment]
One last question: Is `GetRated` aware of users not 'owning' the app? Or does the prompt still appear even though promo code users are not able to create a review?

**Comment by neilmorton** [comment]
No. This is not information that Apple surface within iOS, nor do they surface information to say if the user has previously reviewed or rated etc.
